### PR TITLE
Replace GVN load-widening into vector loads, Disable some GVN Load optimizations

### PR DESCRIPTION
**Pull request by aqjune**
Given a c source like this

```
int f() {
  char x[22];
  init(x);
  return x[16] + x[21];
}
```

I modified GVN::processLoad so it generates IR with vector-type load. Here is the result after -mem2reg -gvn :

```
%0 = bitcast i8* %arrayidx to <8 x i8>*
%1 = load <8 x i8>, <8 x i8>* %0, align 16
%2 = extractelement <8 x i8> %1, i64 0
%conv = sext i8 %2 to i32
%arrayidx1 = getelementptr inbounds [22 x i8], [22 x i8]* %x, i64 0, i64 21
%3 = extractelement <8 x i8> %1, i64 5
%conv2 = sext i8 %3 to i32
%add = add nsw i32 %conv, %conv2
ret i32 %add
```

If the elements are more than 1 byte, then it uses shuffle vector + bitcast :

```
int f_short() {        
  short x[22];         
  init2(x);            
  return x[16] + x[18];
}                      
```

into

```
%0 = bitcast i16* %arrayidx to <8 x i8>*                                      
%1 = load <8 x i8>, <8 x i8>* %0, align 16                                    
%2 = shufflevector <8 x i8> %1, <8 x i8> undef, <2 x i32> <i32 0, i32 1>      
%3 = bitcast <2 x i8> %2 to i16                                               
%conv = sext i16 %3 to i32                                                    
%arrayidx1 = getelementptr inbounds [22 x i16], [22 x i16]* %x, i64 0, i64 18 
%4 = shufflevector <8 x i8> %1, <8 x i8> undef, <2 x i32> <i32 4, i32 5>      
%5 = bitcast <2 x i8> %4 to i16                                               
%conv2 = sext i16 %5 to i32                                                   
%add = add nsw i32 %conv, %conv2                                              
```

Also, GVN now stops getting bits from preceding inclusive load/store.

```
void f2(const int *p, int *q, short *r) {
  const short *sp = (const short *)p;

  *q = *p;
  *r = *sp;
}
```

Previously, after -O2 LLVM optimizes this into

```
%0 = load i32, i32* %p, align 4, !tbaa !1
store i32 %0, i32* %q, align 4, !tbaa !1 
%1 = trunc i32 %0 to i16                 
store i16 %1, i16* %r, align 2, !tbaa !5 
```

However after this patch now it is 

```
%0 = bitcast i32* %p to i16*             
%1 = load i32, i32* %p, align 4, !tbaa !1
store i32 %1, i32* %q, align 4, !tbaa !1 
%2 = load i16, i16* %0, align 2, !tbaa !5
store i16 %2, i16* %r, align 2, !tbaa !5 
```

One more optimization disabled is that now GVN load-widening does not do widening between different types. It is because this case is closely related to the optimization done on `f2` above, and handling each case independently needs extra effort.

```
int f3() {                          
  char x[22];
  short *sx;
  init(x);
  return *(short *)(&x[16]) + x[21];
}
```

Previously after -O2 this was optimized into

```
%1 = bitcast i8* %arrayidx to i64*
%2 = load i64, i64* %1, align 16  
%3 = trunc i64 %2 to i32          
%sext = shl i32 %3, 16
%conv = ashr exact i32 %sext, 16 // this is *(short *)(&x[16])
%4 = lshr i64 %2, 40              
%sext45 = shl nuw nsw i64 %4, 24  
%sext4 = trunc i64 %sext45 to i32 
%conv2 = ashr exact i32 %sext4, 24 // this is x[21]
%add = add nsw i32 %conv2, %conv  
```

But in this patch it is

```
%1 = bitcast i8* %arrayidx to i16*                                         
%2 = load i16, i16* %1, align 16, !tbaa !1                                 
%conv = sext i16 %2 to i32                                                 
%arrayidx1 = getelementptr inbounds [22 x i8], [22 x i8]* %x, i64 0, i64 21
%3 = load i8, i8* %arrayidx1, align 1, !tbaa !5                            
%conv2 = sext i8 %3 to i32                                                 
%add = add nsw i32 %conv2, %conv                                           
call void @llvm.lifetime.end(i64 22, i8* %0) #3                            
```

### CODE REVIEW

**Comment by nunoplopes** [comment]
The 2nd example didn't need shufflevector; the load could be of i16 elements instead. Would get rid of the bitcasts.

**Comment by aqjune** [comment]
I modified the source code as you said so that it can use integer bigger than i8 as an element type.
When GVN tries to widen load, it takes two loads, widen the first load, and modify the second load according to the widened load. 
I made check whether the width to widen (i64 in the above example) is divisible by the bitwidth of first loaded value type (i16, in `short` type case), and if it is divisible, I made vector element size equivalent to the first load. (<4 x i16>)
For example, given an input

```
int f_short() {        
  short x[22];         
  init2(x);            
  return x[16] + x[18];
}                      
```

Now GVN makes

```
%arrayidx = getelementptr inbounds [22 x i16], [22 x i16]* %x, i64 0, i64 16 
%0 = bitcast i16* %arrayidx to <4 x i16>*                                    
%1 = load <4 x i16>, <4 x i16>* %0, align 16                                 
%2 = extractelement <4 x i16> %1, i64 0                                      
%conv = sext i16 %2 to i32                                                   
%arrayidx1 = getelementptr inbounds [22 x i16], [22 x i16]* %x, i64 0, i64 18
%3 = extractelement <4 x i16> %1, i64 2                                      
%conv2 = sext i16 %3 to i32                                                  
%add = add nsw i32 %conv, %conv2                                             
```

**Comment by aqjune** [comment]
I upload two .c files that I used to test this PR.
[loadwidening.zip](https://github.com/snu-sf/llvm-freeze/files/500653/loadwidening.zip)
It includes two .c files : test.c , which makes vector type load after optimization, and test.negative.c, which contains optimization disabled by this PR.

**Comment by aqjune** [comment]
I'm keeping some mutants of this implementation in my repo (https://github.com/aqjune/llvm-freeze). 
'Mutant' means : there are 3 ways to modify GVN load optimization : (1) just disable it, (2) fully allow it(which is semantically incorrect), and (3) use vector-wise operation, as stated in https://github.com/snu-sf/llvm-freeze/pull/30#issuecomment-250455542. And also there are two optimizations here : A. load widening, and B. remove load and get preceding larger load. So there are maximum 9 combinations. I'm maintaining 5 kinds among them, in my local repo.

If we modify these GVN optimizations to use finer-grained vector elements (e.g. <64 x i1>), store instruction exhibit peculiar behavior. The bug is reported to https://llvm.org/bugs/show_bug.cgi?id=30615.

**Pull request merged**
